// const data = await data_controller.get_last_registre();
// console.log(data);
import { Elysia } from "elysia";
import routes from "./routes";
import cron_rutines from "./cron_rutines";
const app = new Elysia();
app.use(routes);
app.use(cron_rutines);
app.listen(process.env.PORT ?? 4000);
console.log(`server started at ${app.server?.hostname}:${app.server?.port}`);
